# Generated by Django 2.1.3 on 2018-11-06 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 21, 16, 0, 591191), verbose_name='添加时间'),
        ),
    ]
