# Generated by Django 2.1.3 on 2018-11-09 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181106_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 13, 39, 5, 98868), verbose_name='添加时间'),
        ),
    ]
