# Generated by Django 2.1.3 on 2018-11-14 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181112_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 11, 13, 33, 869518), verbose_name='添加时间'),
        ),
    ]
