# Generated by Django 2.1.3 on 2018-11-24 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181114_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 14, 35, 21, 251106), verbose_name='添加时间'),
        ),
    ]
