# Generated by Django 2.1.3 on 2018-11-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], max_length=200, verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='gender',
            field=models.CharField(choices=[('girl', '女'), ('boy', '男')], max_length=20, verbose_name='性别'),
        ),
    ]
